# -*- coding: utf-8 -*-
"""criptografia de cesar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17K5GwfddrIgMvY-3kx31Fx31uVHc-IcZ
"""

tipo = input("Selecione qual modo você deseja, entre encripitar (1) e desencriptar (2): ")
alfabeto = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']

numero_de_rotacoes = 7

if tipo == "1":
    texto1 =  input("Insira o texto para encriptar: ")
    texto = texto1.lower()
    palavra = ''
    for c in texto: #Para cada letra no texto:
      if c in alfabeto:
        c_index = alfabeto.index(c) #Pegar o índice do C e ver qual é o índice dele no alfabeto
        palavra += alfabeto[(c_index + numero_de_rotacoes) %len(alfabeto)] #Fazer o loop no meu array, pra isso eu pego a soma do índice com o número de rotações que se pediu
      else:                                                                #e dividi-se pelo tamanho do alfabeto (26), o resto dessa divisão se torna o índice buscado para a 
        palavra += c                                                       #letra no array "alfabeto"
    print("A palavra sairá como: ",palavra)

elif tipo == "2":
    texto1   =  input("Insira o texto para descriptografar: ")
    texto = texto1.lower()
    palavra = ''
    for c in texto:
      if c in alfabeto:
        c_index = alfabeto.index(c)
        palavra += alfabeto[(c_index - numero_de_rotacoes) %len(alfabeto)] #A mesma coisa, mas subtrai-se ao invés de somar-se... 
      else:
        palavra += c
    print("A palavra sairá como: ",palavra)

else:
  print("Você digitou uma opção inválida")