# -*- coding: utf-8 -*-
"""Questão 3 trabalho 2 avaliação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcwvR33Wl_Y1H_nz4HtxmqQFOvewilZn
"""

pergunta = input("Qual função modular você deseja? ")
if pergunta == "soma" or pergunta == "Soma" or pergunta == "SOMA" or pergunta == "s":
    a = int(input("Digite o valor de A: "))
    b = int(input("Digite o valor de B: "))
    mod = int(input("Digite o valor de mod: "))
    print("A equação: ",a," + ",b, " mod",mod) 
    resposta = (a + b) % mod
    print("A resposta:" , resposta)
elif pergunta == "subtração" or pergunta == "Subtração" or pergunta == "SUBTRAÇÃO" or pergunta == "sub":
    a = int(input("Digite o valor de A: "))
    b = int(input("Digite o valor de B: "))
    mod = int(input("Digite o valor de mod: "))
    print("A equação: ",a," - ",b, " mod",mod) 
    resposta = (a - b) % mod
    print("A resposta:" , resposta)
elif pergunta == "multiplicação" or pergunta == "Multiplicação" or pergunta == "MULTIPLICAÇÃO" or pergunta == "m":
    a = int(input("Digite o valor de A: "))
    b = int(input("Digite o valor de B: "))
    mod = int(input("Digite o valor de mod: "))
    print("A equação: ",a," * ",b, " mod",mod) 
    resposta = (a * b) % mod
    print("A resposta:" , resposta)
elif pergunta == "divisão" or pergunta == "Divisão" or pergunta == "DIVISÃO" or pergunta == "d":
    a = int(input("Digite o valor de A: "))
    b = int(input("Digite o valor de B: "))
    mod = int(input("Digite o valor de mod: "))
    c = int(0)
    resultado_da_mult = int()
    if c < b and resultado_da_mult != 1:
      for c in range(mod+1):
        resultado_da_mult = (b*c)%mod
        if resultado_da_mult == 1:
          print("A equação: ",a," / ",b, " mod",mod) 
          resposta = (a*c) % mod
          print("A resposta:" , resposta)
          break
        elif c == mod:
          print("Divisão impossível.")     
else:
    print("Você colocou uma função inexistente")